### PR TITLE
make_kprs func - do not concat str, simplify 'if' statement

### LINKED ISSUE #1: make_kprs func - do not concat str, simplify 'if' statement
ease reading

### PR DESCRIPTION
**Pull request by hpfn-d**
close #1

### CODE REVIEW

**Comment by hpfn-d** [comment]
Hi @h01ger,

New repo - hpfn-d. I lost access to the old  one.

One patch for piupartslib.dwke.py file before 'imports'.

 piupartslib/dwke.py - make_kprs func:
       - list comprehensions and instead
         of nested for loops
       - .join() instead of concat strings
       - simplify 'if' statement

Reason is; two files
 - master-bin/detect_well_known_errors.py
 - piuparts-report.py

do a 'from piupartslib.dwke import *' and I would like to
do a single patch for it. I will tell why at the moment.



Regards,
Herbert

**Comment by h01ger** [comment]
Hi Herbert,

On Sun, Feb 03, 2019 at 04:46:18AM -0800, hpfn-d wrote:
> New repo - hpfn-d. I lost access to the old  one.

ok

> One patch for piupartslib.dwke.py file before 'imports'.
> 
>  piupartslib/dwke.py - make_kprs func:
>        - list comprehensions and instead
>          of nested for loops
>        - .join() instead of concat strings
>        - simplify 'if' statement

is that python2.7 compatible?


-- 
tschüß,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by hpfn-d** [comment]
On 2/5/19 11:27 AM, Holger Levsen wrote:
> Hi Herbert,
> 
> On Sun, Feb 03, 2019 at 04:46:18AM -0800, hpfn-d wrote:
>> New repo - hpfn-d. I lost access to the old one.
> 
> ok
> 
>> One patch for piupartslib.dwke.py file before 'imports'.
>>
>> piupartslib/dwke.py - make_kprs func:
>> - list comprehensions and instead
>> of nested for loops
>> - .join() instead of concat strings
>> - simplify 'if' statement
> 
> is that python2.7 compatible?
> 

I believe yes. Simple prompt tests:


hpfn@debian-main:~$ python2.7 
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> l = ["ola" for i in range(3)]
>>> l = ''.join(l)
>>> l
'olaolaola'
>>> if not l: print 'hi'
... 
>>> l = ["" for i in range(3)]
>>> l = ''.join(l)
>>> if not l: print 'hi'
... 
hi
>>> w = 'w'
>>> if not w in ['pass']: print 'hi'
... 
hi
>>> if w != 'pass': print 'hi'
... 
hi
>>>



Regards,
Herbert

**Comment by h01ger** [comment]
On Tue, Feb 05, 2019 at 02:00:17PM +0000, hpfn-d wrote:
> > is that python2.7 compatible?
> I believe yes. Simple prompt tests:

thanks, merged & deploying...


-- 
tschüß,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by hpfn-d** [comment]
Thanks ho1ger.

**Pull request closed without merging**
